<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Foundation Starter Template</title>
    <link rel="stylesheet" href="assets/css/foundation.css" />
    <link rel="stylesheet" href="assets/css/foundation-float.css" />
    <link rel="stylesheet" href="assets/css/foundation-prototype.css" />
    <link rel="stylesheet" href="assets/css/foundation-icons.css" />
    <link rel="stylesheet" href="assets/css/docs.css" />
</head>
<body>
<div data-sticky-container>
    <div class="top-bar" data-sticky data-margin-top="0" id="example-menu">
        <div class="top-bar-left">
            <ul class="menu">
                <li class="menu-text">Food Management Software</li>
            </ul>
        </div>
        <div class="top-bar-right">
            <ul class="dropdown menu" data-dropdown-menu>
                <li><a href="#">Home</a></li>
                <li>
                    <a href="#first">Inventory</a>
                    <ul class="menu vertical">
                        <li><a href="#">Items</a></li>
                        <li><a href="#">Items - Browse Availability</a></li>
                        <li><a href="#">Items - Grid View</a></li>
                        <li><a href="#">Items Substitution</a></li>
                        <li><a href="#">Items Substitution - Grid</a></li>
                        <li><a href="#">Required Inventory</a></li>
                        <li><a href="#">Inventory Quality Expired / Expiring Items</a></li>
                        <li><a href="#">Codes</a>
                            <ul class="menu vertical">
                                <li><a href="#">Code One</a></li>
                                <li><a href="#">Code Two</a></li>
                                <li><a href="#">Code Three</a></li>
                            </ul>
                        </li>
                        <li><a href="#">Processing</a>
                            <ul class="menu vertical">
                                <li><a href="#">Processing One</a></li>
                                <li><a href="#">Processing Two</a></li>
                                <li><a href="#">Processing Three</a></li>
                            </ul>
                        </li>
                        <li><a href="#">Adjustments</a></li>
                        <li><a href="#">Transfer Orders</a></li>
                        <li><a href="#">Physical (Multiple)</a></li>
                        <li><a href="#">Physical (Single)</a></li>
                        <li><a href="#">View Reserved Lots</a></li>
                        <li><a href="#">Reports</a>
                            <ul class="menu vertical">
                                <li><a href="#">Master List</a></li>
                                <li><a href="#">On Hand</a></li>
                                <li><a href="#">On Hand - Required</a></li>
                                <li><a href="#">Accrued Inventory</a></li>
                                <li><a href="#">Inventory Adjustment</a></li>
                                <li><a href="#">Inventory Status</a></li>
                                <li><a href="#">Available Inventory</a></li>
                                <li><a href="#">Inventory Tracking Guide</a></li>
                                <li><a href="#">Inventory Quality</a></li>
                                <li><a href="#">Count Sheets</a></li>
                                <li><a href="#">Uncounted Report</a></li>
                                <li><a href="#">Inventory Log</a></li>
                                <li><a href="#">Usage Report</a>
                                    <ul class="menu vertical">
                                        <li><a href="#">Report One</a></li>
                                        <li><a href="#">Report Two</a></li>
                                        <li><a href="#">Report Three</a></li>
                                    </ul>
                                </li>
                                <li><a href="#">Production Reports</a>
                                    <ul class="menu vertical">
                                        <li><a href="#">Production Report One</a></li>
                                        <li><a href="#">Production Report Two</a></li>
                                        <li><a href="#">Production Report Three</a></li>
                                    </ul>
                                </li>
                                <li><a href="#">Dormant Items</a></li>
                                <li><a href="#">Partial Lots</a></li>
                                <li><a href="#">Inventory Movements</a></li>
                                <li><a href="#">Overstocked Report</a></li>
                                <li><a href="#">Missing Date Report</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li><a disabled="true" href="#second">Purchases</a></li>
                <li><a href="#third">Orders</a></li>
                <li><a href="#third">Payables</a></li>
                <li><a href="#third">Receivables</a></li>
                <li><a href="#third">Ledger</a></li>
                <li><a href="#third">Pricing</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="container">
    &nbsp;
</div>




<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="assets/js/vendor.js"></script>
<script src="assets/js/foundation.js"></script>
<script>
    $(document).foundation();
</script>
</body>
</html>