<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Foundation Starter Template</title>
    <link rel="stylesheet" href="assets/css/foundation.css" />
    <link rel="stylesheet" href="assets/css/foundation-float.css" />
    <link rel="stylesheet" href="assets/css/foundation-prototype.css" />
    <link rel="stylesheet" href="assets/css/foundation-icons.css" />
    <link rel="stylesheet" href="assets/css/docs.css" />
</head>
<body>
<div class="grid-container vertical-center medium-5 small-11 bordered shadow padding-3">
    <div class="grid-x grid-padding-x align-center-middle">
        <form class="medium-8 small-11 end" method="get" action="/dashboard">
            <div class="medium-12 cell">
                <label>Username
                    <input type="text" placeholder="Your email address">
                </label>
            </div>
            <div class="medium-12 cell">
                <label>Password
                    <input type="password" placeholder="Your password">
                </label>
            </div>
            <div class="medium-12 cell">
                <button type="submit" class="button primary medium-5 small-8 float-center">Enter</button>
            </div>
        </form>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="assets/js/vendor.js"></script>
<script src="assets/js/foundation.js"></script>
<script>
    $(document).foundation();
</script>
</body>
</html>